### ISSUE TITLE
Add missing tests

### ISSUE THREAD

**Issue by duncdrum** [eeditiones/roaster#16]
It would be good to include links to the roaster tests which are part of tei-publisher as mentioned in the readme. 

I think it would be even better if the tests for roaster would all be part of the roaster repo. But having tests executed and located outside of this repo complicates contributing unnecessarily imv.

**Comment by wolfgangmm** [comment]
Well, the tests in tei-publisher-app test the TEI Publisher API and should probably stay where they are to avoid regressions. They may also cover more roaster features than the tests here, but then we should rather create more separate tests for roaster.

**Comment by line-o** [comment]
We need tests for 

- authentication (default and custom methods) and 
- authorization (x-constraints with groups and or users)

**Comment by line-o** [comment]
we should revisit this issue now that #30 was merged

**Comment by line-o** [comment]
We are now at 77 tests total

**Comment by line-o** [comment]
@duncdrum do you agree we can close this?

**Comment by line-o** [comment]
The tests specifically cover authorisation and authentication
