### ISSUE TITLE
Version string in xar does not match git tag

### ISSUE THREAD

**Issue by duncdrum** [eeditiones/roaster#17]
The xar for the 1.1.0 release is using 1.0.0 as semver. I think we need to call the commit analyzer as part of the gulp build to determine the correct version during the build. 

Alternatively we could fiddle with naming of the xar file via `.releaserc` but that might lead to mismatches of the version that’s part of the xar filename and its contents

**Comment by line-o** [comment]
@duncdrum for semantic release to work the package.json should have no version info. 
Hmmm, I did not think about this. But this will mean no local releases, which could be a good thing :)

**Comment by line-o** [comment]
I will remove the version from the package.json and mark it as fixing this issue. This should trigger a 1.1.1 release and we will at least know if it fixes the issue.
