### ISSUE TITLE
Valid XML in POST-Request is rejected

### ISSUE THREAD

**Issue by Bpolitycki** [eeditiones/roaster#42]
## Expected Behaviour

Upload XML-data via Post-Requests with ‚Content-Type: application/xml'.

## Actual Behaviour

Every XML, which is a bit more complex than `<root/>` (used `mediatype.test.js`) e.g. `<root><p>hello world</p></root>` is rejected by roaster. The problem is caused by `let $_test := parse-xml($data)` in [router.xql](https://github.com/eeditiones/roaster/blob/35be50dec2aacf991ddda6033e2ac94840509c18/content/router.xql#L329). 

## Possible Solution

- wrap `parse-xml($data)` in a try-catch-Block
- a bit more complex testcase

**Comment by line-o** [comment]
Thank you for reporting this issue. I will have a look at it in the next days.
