### ISSUE TITLE
Accepting application/json-patch+json

### ISSUE THREAD

**Issue by ahenket** [eeditiones/roaster#47]
We use HTTP PATCH. RFC 6902 that describes behavior says to use application/json-patch+json. When you try that with roaster it will fail:

```json
{
  "code": "errors:BODY_CONTENT_TYPE",
  "description": "Body with media type 'application/json-patch+json' could not be parsed (invalid JSON)."
}
```

Using `Accept: application/json` will present no issue on the exact same input data. I think this is because there are two pieces of logic for mediaType in router.xql:

* router:content-type($request)

```xquery
"format": 
    if ($media-type = ("application/json", "text/json")) 
    then "json" 
    else if ($media-type = ("application/xml", "text/xml"))
    then "xml"
    else if ($media-type = "multipart/form-data")
    then "form-data"
    else if ($format-hint) 
    then $format-hint 
    else "binary"
```

* router:method-for-content-type($type)

```xquery
switch (substring-before($type, "/"))
    case "application" return
        if (ends-with($type, "json")) then "json" (: matches application/json and any type ending in +json :)
        else if (ends-with($type, "xhtml+xml")) then "xhtml"
        else if (ends-with($type, "xml")) then "xml" (: matches application/xml and any type ending in +xml :)
        else "text"
    case "text" return
        if (ends-with($type, "/xml")) then "xml"
        else if (ends-with($type, "/html")) then "html5"
        else "text"
    case "image" return
        if (ends-with($type, "/svg+xml")) then "xml"
        else "text"
    case "multipart"
    case "audio"
    case "font"
    case "example"
    case "message"
    case "model"
    case "video" return 
        "text" (: assume binary content :)
    default return 
        error($errors:OPERATION, "Unknown media type '" || $type || '"') 
```

The latter code would happily parse application/json-patch+json as being a json request. The former does not. Could these two functions be synced so HTTP PATCH can be properly supported?

**Comment by line-o** [comment]
I agree, we should do that.

**Comment by line-o** [comment]
Relooking at this I wonder why `$format-hint` does not work as intended.

**Comment by line-o** [comment]
The error message even mentions that the error is not an unsupported media type but the contents of if not being valid JSON

> Body with media type 'application/json-patch+json' could not be parsed (invalid JSON).

**Comment by line-o** [comment]
@ahenket can you please provide an example requestBody that you are sending that triggers the error.

**Comment by line-o** [comment]
Example found in the [RFC 6902](https://www.rfc-editor.org/rfc/rfc6902)

```json
[
     { "op": "test", "path": "/a/b/c", "value": "foo" },
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
]
```

**Comment by line-o** [comment]
see also https://github.com/eXist-db/exist/issues/4560
