### ISSUE TITLE
http patch not implemented?

### ISSUE THREAD

**Issue by ahenket** [eeditiones/roaster#5]
I'm trying to implement the [RFC6902](https://tools.ietf.org/html/rfc6902) spec, but PATCH never seems to be reaching my code:

```bash
curl -X PATCH "[host]/[path]" \
       -H  "accept: application/json" \
       -H  "Content-Type: application/json" \
       -d "[json body]" -v
```

yields:

```bash
< HTTP/1.1 501 Not Implemented
< Access-Control-Expose-Headers: pb-start, pb-total
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
< Access-Control-Allow-Headers: Content-Type, api_key, Authorization
< Content-Length: 0
< Server: Jetty(9.4.26.v20200117)
```

Note that Access-Control-Allow-Methods actually mentions PATCH, but nonetheless the http 501 is not my doing. Can I configure this somewhere?

**Comment by line-o** [comment]
The HTTP status code 501 is definitely not set in roaster. That can only mean the issue originates lower down in the servlet.

**Comment by ahenket** [comment]
The Jetty documentation is awkwardly silent on the methods (any). eXist-db RestXQ was [patched by Adam](https://github.com/exquery/exquery/pull/88/commits/73fcb4932aabc4827dce9e8b0c0bf61b08c8ab04) for HTTP PATCH. I'm not sure where to look next.

**Comment by line-o** [comment]
I will open an issue on existdb. `javax.servlet.http.HttpServlet` is extended by the database and we can therefore add support for patch overriding the `service` method.

**Comment by line-o** [comment]
Related issue: https://github.com/eXist-db/exist/issues/3698

**Comment by line-o** [comment]
eXist-db/exist#3698 was merged :tada:
That means you can use PATCH in your API definition starting with the next release of eXistdb.
