### ISSUE TITLE
INFO logging

### ISSUE THREAD

**Issue by wolfgangmm** [eeditiones/roaster#67]
Roaster is now very chatty and logs a lot of messages to the INFO logs. This makes it difficult to debug your own functions. Roaster should probably log requests to DEBUG instead of INFO.

**Comment by line-o** [comment]
I was thinking about an application logger which would then go into a separate `roaster.log`. What do you think?

**Comment by line-o** [comment]
For anyone having this problem at the moment you can filter out roasters INFO messages with `grep -ve "INFO.*roaster"`.

Example with a tail on exist.log

```
tail -f exist.log | grep -ve "INFO.*roaster"
```

**Comment by line-o** [comment]
It is still under consideration to allow applications to pass in custom log function to `roaster:route` as a fourth parameter.
